# Generated by Django 5.0.2 on 2025-03-05 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PestisidaPupuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.TextField(choices=[('PESTISIDA', 'Pestisida'), ('PUPUK', 'Pupuk')], max_length=10)),
                ('nama_obat', models.CharField(db_index=True, max_length=100, unique=True)),
                ('produsen', models.CharField(max_length=100)),
                ('warna', models.TextField(choices=[('HITAM', 'Hitam'), ('PUTIH', 'Putih'), ('MERAH', 'Merah'), ('KUNING', 'Kuning')], max_length=10)),
                ('deskripsi', models.TextField(default='Deskripsi Obat')),
            ],
            options={
                'db_table': 'pestisida_pupuk',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Hama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_hama', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rate_bahaya', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1)),
                ('makhluk', models.CharField(choices=[('TUMBUHAN', 'Tumbuhan'), ('HEWAN', 'Hewan')], max_length=20)),
                ('deskripsi', models.TextField(default='Deskripsi Hama')),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='farming_v3.pestisidapupuk')),
            ],
            options={
                'db_table': 'hama',
                'ordering': ['-rate_bahaya'],
            },
        ),
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_tanaman', models.CharField(db_index=True, max_length=100, unique=True)),
                ('jenis', models.CharField(max_length=100)),
                ('waktu_tanam_hari', models.IntegerField(default=0)),
                ('harga_perTon', models.BigIntegerField(default=0)),
                ('deskripsi', models.TextField(default='deskripsi tanaman')),
                ('link_tanaman', models.URLField(blank=True, default='https://trans89.com/media/upload/2022/10/Tangerang-Dorong-Pasar-Besar-Sektor-Pertanian-Dengan-Budidaya-Tanaman-Pangan-Organik-653x366.jpg', null=True)),
                ('public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanaman', to=settings.AUTH_USER_MODEL)),
                ('peluang_hama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_v3.hama')),
            ],
            options={
                'db_table': 'tanaman',
                'ordering': ['-harga_perTon'],
            },
        ),
        migrations.CreateModel(
            name='Panenan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('berat_ton', models.BigIntegerField(default=0)),
                ('deskripsi', models.TextField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='panenan', to=settings.AUTH_USER_MODEL)),
                ('hasil_panen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='farming_v3.tanaman')),
            ],
            options={
                'db_table': 'panenan',
                'ordering': ['created'],
            },
        ),
    ]
