# Generated by Django 5.1.4 on 2025-01-28 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PestisidaPupuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.TextField(choices=[('PESTISIDA', 'Pestisida'), ('PUPUK', 'Pupuk')], max_length=10)),
                ('nama_obat', models.CharField(max_length=100, unique=True)),
                ('produsen', models.CharField(max_length=100)),
                ('warna', models.TextField(choices=[('HITAM', 'Hitam'), ('PUTIH', 'Putih'), ('MERAH', 'Merah'), ('KUNING', 'Kuning')], max_length=10)),
            ],
            options={
                'db_table': 'pestisida_pupuk',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Hama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_hama', models.CharField(max_length=100, unique=True)),
                ('rate_bahaya', models.IntegerField(default=0)),
                ('makhluk', models.CharField(choices=[('TUMBUHAN', 'Tumbuhan'), ('HEWAN', 'Hewan')], max_length=20)),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='farming_v3.pestisidapupuk')),
            ],
            options={
                'db_table': 'hama',
                'ordering': ['-rate_bahaya'],
            },
        ),
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_tanaman', models.CharField(max_length=100, unique=True)),
                ('jenis', models.CharField(max_length=100)),
                ('waktu_tanam_hari', models.IntegerField(default=0)),
                ('harga_perTon', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanaman', to=settings.AUTH_USER_MODEL)),
                ('peluang_hama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming_v3.hama')),
            ],
            options={
                'db_table': 'tanaman',
                'ordering': ['-harga_perTon'],
            },
        ),
        migrations.CreateModel(
            name='Panenan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('berat_ton', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='panenan', to=settings.AUTH_USER_MODEL)),
                ('hasil_panen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='farming_v3.tanaman')),
            ],
            options={
                'db_table': 'panenan',
                'ordering': ['created'],
            },
        ),
    ]
