# Generated by Django 5.0.2 on 2025-03-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_v3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hama',
            name='rate_bahaya',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Considerable'), (4, 'Dangerous'), (5, 'Extreme')], default=1),
        ),
    ]
