# Generated by Django 5.1.4 on 2025-02-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farming_v3', '0003_panenan_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panenan',
            name='owner',
        ),
    ]
