# Generated by Django 5.1.4 on 2025-02-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_v3', '0009_tanaman_deskripsi_tanaman_link_tanaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='hama',
            name='deskripsi',
            field=models.TextField(default='Deskripsi Hama'),
        ),
        migrations.AddField(
            model_name='panenan',
            name='deskripsi',
            field=models.TextField(default='Deskripsi Panenan'),
        ),
        migrations.AddField(
            model_name='pestisidapupuk',
            name='deskripsi',
            field=models.TextField(default='Deskripsi Obat'),
        ),
    ]
