# Generated by Django 5.1.6 on 2025-02-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_v3', '0010_hama_deskripsi_panenan_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panenan',
            name='deskripsi',
            field=models.TextField(),
        ),
    ]
