# Generated by Django 5.1.6 on 2025-02-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_v3', '0011_alter_panenan_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hama',
            name='nama_hama',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='panenan',
            name='berat_ton',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pestisidapupuk',
            name='nama_obat',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tanaman',
            name='nama_tanaman',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
