# Generated by Django 5.1.6 on 2025-02-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming_v3', '0012_alter_hama_nama_hama_alter_panenan_berat_ton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanaman',
            name='harga_perTon',
            field=models.BigIntegerField(default=0),
        ),
    ]
