services:
  db:
    image: postgres:17
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

  django-web:
    build: .
    container_name: django-docker
    depends_on:
      - db
      - redis
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.prod

  frontend-proxy:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web
  

volumes:
  postgres_data: