# Generated by Django 5.1.3 on 2024-12-07 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PestisidaPupuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.TextField(choices=[('PESTISIDA', 'Pestisida'), ('PUPUK', 'Pupuk')], max_length=10)),
                ('nama_obat', models.CharField(max_length=100)),
                ('produsen', models.CharField(max_length=100)),
                ('warna', models.TextField(choices=[('HITAM', 'Hitam'), ('PUTIH', 'Putih'), ('MERAH', 'Merah'), ('KUNING', 'Kuning')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Petani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('luas_tanah', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['luas_tanah'],
            },
        ),
        migrations.CreateModel(
            name='Hama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_hama', models.CharField(max_length=100)),
                ('rate_bahaya', models.IntegerField(default=0)),
                ('makhluk', models.CharField(choices=[('TUMBUHAN', 'Tumbuhan'), ('HEWAN', 'Hewan')], max_length=20)),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.pestisidapupuk')),
            ],
            options={
                'ordering': ['rate_bahaya'],
            },
        ),
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nama_tanaman', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=100)),
                ('waktu_tanam_hari', models.IntegerField(default=0)),
                ('harga_perTon', models.IntegerField(default=0)),
                ('peluang_hama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.hama')),
            ],
            options={
                'ordering': ['harga_perTon'],
            },
        ),
        migrations.CreateModel(
            name='Panenan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('berat_ton', models.IntegerField(default=0)),
                ('petaninya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.petani')),
                ('hasil_panen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.tanaman')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
