# Generated by Django 5.1.3 on 2024-11-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panenan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil_panen', models.CharField(max_length=100)),
                ('berat_ton', models.IntegerField(default=0)),
                ('waktu_tanam_hari', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Petani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('luas_tanah', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tanaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tanaman', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=100)),
                ('waktu_tanam_hari', models.IntegerField(default=0)),
            ],
        ),
    ]
