# Generated by Django 5.1.3 on 2024-12-19 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hama',
            name='obat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farming.pestisidapupuk'),
        ),
        migrations.AlterField(
            model_name='panenan',
            name='hasil_panen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farming.tanaman'),
        ),
        migrations.AlterField(
            model_name='panenan',
            name='petaninya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farming.petani'),
        ),
    ]
