# Generated by Django 5.1.3 on 2024-12-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0003_alter_hama_obat_alter_panenan_hasil_panen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hama',
            options={'ordering': ['-rate_bahaya']},
        ),
        migrations.AlterModelOptions(
            name='petani',
            options={'ordering': ['-luas_tanah']},
        ),
        migrations.AlterModelOptions(
            name='tanaman',
            options={'ordering': ['-harga_perTon']},
        ),
        migrations.AddConstraint(
            model_name='petani',
            constraint=models.UniqueConstraint(fields=('username', 'nama'), name='unique_username_nama'),
        ),
    ]
